server:
  port: 8080

spring:
  datasource:
    password: root
    name: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idlebugs?userUnicode=true&characterEncoding-UTF-8
