server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idlebugs?userUnicode=true&characterEncoding-UTF-8
    password: root
    username: root
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-not-delete-value: 0
        logic-delete-value: 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

weixin:
  appid: wxf3c9f3b16d188314
  secret: 42420fd8e88db05d9168f82ba10966e4
